### ISSUE TITLE
Do we actually need auto-build in DockerHub?

### ISSUE THREAD

**Issue by maxulysse** [nf-core/logos#22]
Do we even need images for this repo?

**Comment by ewels** [comment]
Where do you see that? There's no `Dockerfile` so I'm not sure what it would build..?

**Comment by maxulysse** [comment]
Now that I think about it, I think I put a Dockerfile at some point, but we removed it when we added the logo generation to the website.
But the auto-built was still there.
I just removed it.
Do we keep the dockerhub repo or can we kill it?

**Comment by maxulysse** [comment]
And saw the error message in my mail box from Dockerhub.
I try to pay attention to the error messages from time to time

**Comment by ewels** [comment]
Ah ok. Fine by me to delete the repo I think.

**Comment by maxulysse** [comment]
Done
