### ISSUE TITLE
Demultiplex is too long

### ISSUE THREAD

**Issue by Emiller88** [nf-core/logos#26]
```sh
curl https://nf-co.re/logo/demultiplex?theme=dark --output nfcore-pipelinename_logo_dark.png
```
Fails to make an image but

```sh 
curl https://nf-co.re/logo/demultiplx?theme=dark --output nfcore-pipelinename_logo_dark.png
curl https://nf-co.re/logo/demultiple?theme=dark --output nfcore-pipelinename_logo_dark.png
```

Both work.

**Comment by Emiller88** [comment]
Hmm but 
```sh
curl https://nf-co.re/logo/superlongword?theme=dark --output nfcore-pipelinename_logo_dark.png
```
Works 🤔

**Comment by ewels** [comment]
Ah it'll be because the broken version is held in the cache, so it's just returning that every time. I think that there's a flag to bust the cache for an image?

**Comment by ewels** [comment]
Yeah, `?f` (undocumented).

ok I just loaded it with that and now the cached version should be fixed. Try again and it should work 😊
