### ISSUE TITLE
Make social preview image

### ISSUE THREAD

**Issue by ewels** [nf-core/logos#6]
GitHub repos can now have "social preview" images, on the Settings page:

![image](https://user-images.githubusercontent.com/465550/57291760-5abedb80-70c0-11e9-8cea-918879cce401.png)

These need to have specific dimensions. For pipelines, it would be great to have the pipeline logo and pipeline URL, plus the nf-core URL. Maybe also free text for a description?

GitHub provide a template:
![repository-open-graph-template](https://user-images.githubusercontent.com/465550/57291808-79bd6d80-70c0-11e9-9679-ce7b223056ed.png)

The nf-core logos command could make these images as well as the logo for the readme.

**Comment by MaxUlysse** [comment]
We now have social previews for all pipelines, I made PR #18 to include all source files + script to generate pngs.
